(() => {
  'use strict';
  const token = window.LOCAL_MANAGER_TOKEN;
  const labels = {profile:'主页文案',news:'学术动态',education:'教育经历',projects:'科研项目',service:'学术服务',personalAwards:'个人荣誉',studentAwards:'学生获奖',publications:'论文成果',files:'PDF 材料',publish:'提交到 GitHub',log:'修改记录'};
  const order = Object.keys(labels);
  const main = document.getElementById('main');
  let snapshot, current = 'profile', editing = null, query = '', knownFiles = [];
  const esc = v => String(v ?? '').replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  const tr = (v, lang='zh') => typeof v === 'object' && v ? v[lang] || v.en || '' : v || '';
  const entries = category => category === 'service' ? snapshot.data.service.flatMap((group, groupIndex) => group.items.map((item, index) => ({item,index,groupIndex,groupTitle:tr(group.title)}))) : snapshot.data[category].map((item,index) => ({item,index}));
  const label = (category,item) => tr(item.title || item.name || item.degree || item.years) || item.title || '条目';
  function toast(message, error=false){ const el=document.getElementById('toast');el.textContent=message;el.style.background=error?'#9b392d':'#17323a';el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),6500); }
  async function api(route, options={}) { const response=await fetch('/api/'+route,{...options,headers:{'X-Manager-Token':token,...options.headers}}); const value=await response.json(); if(!response.ok) throw new Error(value.error||'请求失败'); return value; }
  async function jsonPost(route,body){return api(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}
  function nav(){document.getElementById('nav').innerHTML=order.map(k=>`<button type="button" data-nav="${k}" class="${current===k?'active':''}">${labels[k]}</button>`).join('');}
  function render(){nav();if(current==='profile') renderProfile(); else if(current==='files') renderFiles(); else if(current==='publish') renderPublish(); else if(current==='log') renderLog(); else renderRecords();}
  function field(name,title,value='',type='text',hint=''){return `<label class="field"><span>${title}</span>${type==='textarea'?`<textarea name="${name}">${esc(value)}</textarea>`:type==='select'?`<select name="${name}">${value}</select>`:`<input name="${name}" type="${type}" value="${esc(value)}">`}${hint?`<p class="hint">${hint}</p>`:''}</label>`;}
  function pair(key,title,value={}){return `<div class="grid2">${field(key+'_zh',title+' · 中文',value.zh||'')}${field(key+'_en',title+' · English',value.en||'')}</div>`;}
  function lineField(key,title,value={}){return `<div class="grid2">${field(key+'_zh',title+' · 中文',value.zh||'','textarea')}${field(key+'_en',title+' · English',value.en||'','textarea')}</div>`;}
  function filesText(items,project=false){return (items||[]).map(x=>project?`${x.path} | ${tr(x.label,'zh')} | ${tr(x.label,'en')}`:x.path).join('\n');}
  function uploadWidget(category){if(category==='education')return '';const project=category==='projects';return `<div class="upload"><strong>上传并关联到当前${labels[category]}</strong><p class="hint">选择 A4、5 MB 以下的 PDF。上传后将自动填入上方材料字段，请继续保存条目。</p><div class="upload-row"><input id="attach-file" type="file" accept="application/pdf,.pdf"><button class="secondary" type="button" id="attach-upload">上传并填入</button></div>${project?`<div class="grid2">${field('attachment_label_zh','材料名称 · 中文','批准通知书 PDF')}${field('attachment_label_en','Document label · English','Project approval PDF')}</div>`:''}<p id="attach-result" class="status" hidden></p></div>`;}
  function recordFields(category,item){let out='';
    if(category==='education') out=field('years','学习年份',item.years)+pair('degree','学位',item.degree)+pair('school','学校',item.school);
    if(category==='publications') out=field('title','论文标题',item.title)+field('year','发表年份',item.year||'','number')+field('citation','Google Scholar 原始引文',item.citation,'textarea')+field('gbtCitation','简历用 GB/T 7714—2025 引文',item.gbtCitation||'','textarea','留空会按原始引文自动生成；核对出版信息后可在此修订。编号由简历自动添加。')+field('scholar','本人 Google Scholar 中的该论文链接',item.scholar||'','url')+field('area','论文分类',Object.entries(snapshot.data.areas).map(([key,value])=>`<option value="${key}" ${item.area===key?'selected':''}>${esc(value.zh)} / ${esc(value.en)}</option>`).join(''),'select')+field('file','全文 PDF 路径（可留空）',item.file||'');
    if(category==='projects') out=pair('title','项目名称',item.title)+pair('funder','资助来源',item.funder)+pair('role','承担角色',item.role)+lineField('note','项目说明（可留空）',item.note)+field('files','项目材料',filesText(item.files,true),'textarea','每行：PDF 路径 | 中文材料名 | English name');
    if(category==='news') out=field('year','年份',item.year||'','number')+pair('title','动态标题',item.title)+lineField('detail','正文',item.detail)+field('file','证明 PDF 路径（可留空）',item.file||'');
    if(category==='personalAwards'||category==='studentAwards') out=field('year','获奖年份',item.year||'','number')+pair('title','奖项名称',item.title)+lineField('note','说明（可留空）',item.note)+field('files','证明 PDF 路径',filesText(item.files),'textarea','每行一个 assets/ 路径；至少填写一份。');
    if(category==='service') out=field('groupIndex','所属分组',snapshot.data.service.map((g,i)=>`<option value="${i}" ${i===editing?.groupIndex?'selected':''}>${esc(tr(g.title))}</option>`).join(''),'select')+pair('name','任职名称',item.name)+field('file','证明 PDF 路径（可留空）',item.file||'');
    return out+uploadWidget(category);
  }
  function formValue(form,key){return form.elements.namedItem(key)?.value.trim()||'';}
  function getPair(form,key){return {zh:formValue(form,key+'_zh'),en:formValue(form,key+'_en')};}
  function parseFiles(text,project){return text.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const parts=line.split('|').map(x=>x.trim());return project?{path:parts[0],label:{zh:parts[1]||'',en:parts[2]||''}}:{path:parts[0]};});}
  function parseRecord(category,form){
    if(category==='education') return {years:formValue(form,'years'),degree:getPair(form,'degree'),school:getPair(form,'school')};
    if(category==='publications') return {title:formValue(form,'title'),year:formValue(form,'year'),citation:formValue(form,'citation'),gbtCitation:formValue(form,'gbtCitation'),scholar:formValue(form,'scholar'),area:formValue(form,'area'),file:formValue(form,'file')};
    if(category==='projects') return {title:getPair(form,'title'),funder:getPair(form,'funder'),role:getPair(form,'role'),note:getPair(form,'note'),files:parseFiles(formValue(form,'files'),true)};
    if(category==='news') return {year:formValue(form,'year'),title:getPair(form,'title'),detail:getPair(form,'detail'),file:formValue(form,'file')};
    if(category==='personalAwards'||category==='studentAwards') return {year:formValue(form,'year'),title:getPair(form,'title'),note:getPair(form,'note'),files:parseFiles(formValue(form,'files'),false)};
    return {name:getPair(form,'name'),file:formValue(form,'file')};
  }
  function renderRecords(){const rows=entries(current); const filtered=rows.filter(x=>!query||JSON.stringify(x.item).toLowerCase().includes(query.toLowerCase()));
    main.innerHTML=`<section class="panel"><h2>${labels[current]}</h2><p class="muted">共 ${rows.length} 项。保存后会同步更新本地网站与内容索引，点击“提交到 GitHub”才会发布。</p><div class="toolbar"><input id="search" type="search" placeholder="搜索本栏目" value="${esc(query)}"><button class="primary" data-new>＋ 新增条目</button></div><div id="records">${filtered.map(x=>`<div class="record"><div><strong>${esc(label(current,x.item))}</strong><small>${x.item.year||x.item.years||''}${x.groupTitle?' · '+esc(x.groupTitle):''}${x.item.file||x.item.files?.length?' · 有 PDF 材料':''}</small></div><div class="actions"><button data-edit="${x.index}" data-group="${x.groupIndex??0}">编辑</button><button data-move="up" data-index="${x.index}" data-group="${x.groupIndex??0}">上移</button><button data-move="down" data-index="${x.index}" data-group="${x.groupIndex??0}">下移</button><button class="delete" data-delete="${x.index}" data-group="${x.groupIndex??0}">删除</button></div></div>`).join('')||'<p class="muted">暂无匹配记录。</p>'}</div></section><div id="editor"></div>`;
    if(editing) renderEditor();
  }
  function renderEditor(){const category=current, item=editing?.item||{};const el=document.getElementById('editor');if(!el)return;el.innerHTML=`<section class="panel"><h3>${editing?.new?'新增':'编辑'}${labels[category]}</h3><form id="record-form">${recordFields(category,item)}${field('noteToAgent','修改备注（可留空）','','textarea','记录在 CONTENT_CHANGELOG.md，方便后续智能体追溯。')}<div class="form-actions"><button class="primary" type="submit">保存到本地</button><button class="secondary" type="button" data-cancel>取消</button></div></form></section>`;el.scrollIntoView({behavior:'smooth',block:'start'});}
  async function recordAction(action,index,groupIndex,record,note=''){const result=await jsonPost('records',{revision:snapshot.revision,category:current,action,index,groupIndex,record,note});snapshot.data=result.data;snapshot.revision=result.revision;editing=null;render();toast(result.message);}
  function renderProfile(){const p=snapshot.profile;main.innerHTML=`<section class="panel"><h2>主页文案</h2><p class="muted">中英文首页会一起更新。研究方向的名称与论文分类一致，此处可编辑每类的说明。</p><form id="profile-form">${pair('role','职称',p.role)}${lineField('summary','首页简述',p.summary)}<div class="grid2">${field('affiliations_zh','单位 · 中文',p.affiliations.zh.join('\n'),'textarea','每行一个单位')}${field('affiliations_en','Affiliations · English',p.affiliations.en.join('\n'),'textarea','One affiliation per line')}</div><div class="grid2">${field('about_zh','学术经历 · 中文',p.about.zh.join('\n'),'textarea','每行一段')}${field('about_en','Academic background · English',p.about.en.join('\n'),'textarea','One paragraph per line')}</div><h3>研究方向说明</h3>${p.topics.map((x,i)=>`<div class="panel"><strong>${esc(x.title.zh)} / ${esc(x.title.en)}</strong>${lineField('topic'+i,'说明',x.description)}</div>`).join('')}${field('noteToAgent','修改备注（可留空）','','textarea')}<div class="form-actions"><button class="primary" type="submit">保存到本地</button></div></form></section>`;}
  async function saveProfile(form){const p=structuredClone(snapshot.profile);p.role=getPair(form,'role');p.summary=getPair(form,'summary');for(const key of ['affiliations','about'])for(const lang of ['zh','en'])p[key][lang]=formValue(form,key+'_'+lang).split('\n').map(x=>x.trim()).filter(Boolean);p.topics.forEach((topic,i)=>topic.description=getPair(form,'topic'+i));const result=await jsonPost('profile',{revision:snapshot.revision,profile:p,note:formValue(form,'noteToAgent')});snapshot.data=result.data;snapshot.profile=p;snapshot.revision=result.revision;render();toast(result.message);}
  async function renderFiles(){main.innerHTML=`<section class="panel"><h2>PDF 材料</h2><p class="muted">请打开对应的论文、项目、获奖、新闻或学术服务条目，在编辑表单中上传 PDF。上传会自动填入当前条目的材料字段，保存条目后即可发布。</p></section><section class="panel"><h3>已有 PDF 材料</h3><input id="file-search" type="search" placeholder="搜索文件名"><div id="file-list" class="loading">正在读取…</div></section>`;try{knownFiles=(await api('files')).files;updateFileList();}catch(e){toast(e.message,true);}}
  function updateFileList(){const q=document.getElementById('file-search')?.value.toLowerCase()||'';const el=document.getElementById('file-list');if(el)el.innerHTML=knownFiles.filter(x=>x.toLowerCase().includes(q)).map(x=>`<div class="record"><span>${esc(x)}</span><div class="actions"><button data-copy="${esc(x)}">复制路径</button><a href="/site/${esc(x)}" target="_blank" rel="noopener">查看 PDF ↗</a></div></div>`).join('')||'<p class="muted">没有匹配文件。</p>';}
  async function upload(){const form=document.getElementById('record-form'),file=document.getElementById('attach-file').files[0];if(!file)throw new Error('请先选择 PDF 文件');const title=formValue(form,'title_zh')||formValue(form,'title')||formValue(form,'name_zh')||labels[current];const response=await fetch('/api/upload',{method:'POST',headers:{'X-Manager-Token':token,'X-Record-Category':current,'X-Record-Title':encodeURIComponent(title),'X-File-Name':encodeURIComponent(file.name),'Content-Type':'application/pdf'},body:file});const value=await response.json();if(!response.ok)throw new Error(value.error);const fieldName=['projects','personalAwards','studentAwards'].includes(current)?'files':'file';const input=form.elements.namedItem(fieldName);if(fieldName==='file')input.value=value.path;else{const line=current==='projects'?`${value.path} | ${formValue(form,'attachment_label_zh')} | ${formValue(form,'attachment_label_en')}`:value.path;input.value=[input.value.trim(),line].filter(Boolean).join('\n');}const result=document.getElementById('attach-result');result.hidden=false;result.textContent='已自动填入：'+value.path+'。请保存条目。';toast(value.message);}
  async function renderPublish(){main.innerHTML=`<section class="panel"><h2>提交到 GitHub</h2><p class="muted">勾选需要发布的文件。页面会显示所有本地改动，默认勾选网站内容与材料。发布后可访问 cavin-lee.github.io。</p><div id="publish-status" class="loading">正在检查改动…</div><div class="form-actions"><button class="secondary" id="refresh-status">刷新状态</button></div></section>`;await refreshStatus();}
  async function refreshStatus(){try{const s=await api('status');const el=document.getElementById('publish-status');if(!el)return;el.innerHTML=`<p>当前分支：<strong>${esc(s.branch)}</strong>；尚未推送的提交：<strong>${s.ahead}</strong> 个。</p>${s.changes.length?`<h3>待发布文件</h3>${s.changes.map(x=>`<label class="change"><input type="checkbox" data-path="${esc(x.path)}" ${x.recommended?'checked':''}><span>${esc(x.path)} <small>(${esc(x.status)})</small></span></label>`).join('')}`:'<p class="muted">当前没有未提交的文件。</p>'}${field('commit-message','本次发布说明','Update academic website content')}<button class="primary" id="publish-button" ${!s.changes.length&&!s.ahead?'disabled':''}>提交并推送到 GitHub</button><p class="hint">未勾选的文件会保留在电脑上，不会随本次提交发布。</p>`;}catch(e){document.getElementById('publish-status').innerHTML=`<p class="status error">${esc(e.message)}</p>`;}}
  async function publish(){const paths=[...document.querySelectorAll('[data-path]:checked')].map(x=>x.dataset.path);if(!paths.length&&!confirm('本次只推送已有提交，继续吗？'))return;const message=document.querySelector('[name=commit-message]').value;const result=await jsonPost('publish',{paths,message});toast(result.message);await refreshStatus();}
  async function renderLog(){main.innerHTML=`<section class="panel"><h2>修改记录</h2><p class="muted">每次通过管理页面保存内容，都会写入仓库中的 CONTENT_CHANGELOG.md；完整条目索引保存在 CONTENT_INDEX.md。</p><div id="log-content" class="loading">正在读取…</div></section>`;try{const result=await api('log');document.getElementById('log-content').innerHTML=`<pre>${esc(result.text)}</pre>`;}catch(e){toast(e.message,true);}}
  document.addEventListener('click',async event=>{const target=event.target.closest('button');if(!target)return;try{
    if(target.dataset.nav){current=target.dataset.nav;editing=null;query='';render();return;}
    if(target.hasAttribute('data-new')){editing={new:true,item:{},groupIndex:0};renderEditor();return;}
    if(target.hasAttribute('data-edit')){const row=entries(current).find(x=>x.index===Number(target.dataset.edit)&&(x.groupIndex??0)===Number(target.dataset.group||0));editing={...row,new:false};renderEditor();return;}
    if(target.hasAttribute('data-cancel')){editing=null;document.getElementById('editor').innerHTML='';return;}
    if(target.hasAttribute('data-delete')){if(!confirm('确定删除此条目？关联 PDF 文件会保留，之后可重新使用。'))return;await recordAction('delete',Number(target.dataset.delete),Number(target.dataset.group||0));return;}
    if(target.dataset.move){await recordAction(target.dataset.move,Number(target.dataset.index),Number(target.dataset.group||0));return;}
    if(target.id==='attach-upload'){target.disabled=true;try{await upload();}finally{target.disabled=false;}return;}
    if(target.dataset.copy){await navigator.clipboard.writeText(target.dataset.copy);toast('已复制 PDF 路径');return;}
    if(target.id==='refresh-status'){await refreshStatus();return;}
    if(target.id==='publish-button'){target.disabled=true;try{await publish();}finally{target.disabled=false;}return;}
  }catch(e){toast(e.message,true);}});
  document.addEventListener('submit',async event=>{if(!['record-form','profile-form'].includes(event.target.id))return;event.preventDefault();const button=event.target.querySelector('[type=submit]');button.disabled=true;try{if(event.target.id==='profile-form')await saveProfile(event.target);else {const category=current,form=event.target;const groupIndex=category==='service'?Number(formValue(form,'groupIndex')):0;if(category==='service'&&!editing.new&&groupIndex!==editing.groupIndex)throw new Error('如需移动到另一分组，请在新分组新增条目，再删除旧条目');await recordAction(editing.new?'create':'update',editing.new?-1:editing.index,groupIndex,parseRecord(category,form),formValue(form,'noteToAgent'));}}catch(e){toast(e.message,true);}finally{button.disabled=false;}});
  document.addEventListener('input',event=>{if(event.target.id==='search'){query=event.target.value;const start=event.target.selectionStart;renderRecords();const box=document.getElementById('search');box.focus();box.setSelectionRange(start,start);}if(event.target.id==='file-search')updateFileList();});
  api('state').then(value=>{snapshot=value;render();}).catch(error=>{main.innerHTML=`<div class="panel status error">无法打开内容：${esc(error.message)}</div>`;});
})();
